-- SISTEM PERSEDIAAN DAN ANALISIS HPP TOKO MERCHANDISE
-- Jalankan seluruh isi file ini di Supabase Dashboard > SQL Editor > Run.
-- Policy allow-all hanya untuk development tanpa login; batasi sebelum production.

create table if not exists public.produk (
	id bigint generated by default as identity primary key,
	sku text not null unique,
	nama text not null,
	kategori text not null default 'Lainnya',
	ukuran text not null default '',
	stok integer not null default 0 check (stok >= 0),
	stok_minimum integer not null default 5 check (stok_minimum >= 0),
	hpp numeric(14, 2) not null default 0 check (hpp >= 0),
	harga_jual numeric(14, 2) not null default 0 check (harga_jual >= 0),
	created_at timestamptz not null default now()
);

alter table public.produk add column if not exists ukuran text not null default '';
alter table public.produk add column if not exists stok_minimum integer not null default 5;

do $$
begin
	if not exists (select 1 from pg_constraint where conname = 'produk_stok_minimum_nonnegative' and conrelid = 'public.produk'::regclass) then
		alter table public.produk add constraint produk_stok_minimum_nonnegative check (stok_minimum >= 0);
	end if;
end $$;

create table if not exists public.pembelian (
	id bigint generated by default as identity primary key,
	po_id bigint,
	produk_id bigint not null references public.produk(id) on delete restrict,
	qty integer not null check (qty > 0),
	harga_satuan numeric(14, 2) not null check (harga_satuan >= 0),
	biaya_tambahan numeric(14, 2) not null default 0 check (biaya_tambahan >= 0),
	total numeric(14, 2) not null check (total >= 0),
	supplier text not null default '',
	tanggal date not null default current_date,
	created_at timestamptz not null default now()
);

create table if not exists public.pembelian_po (
	id bigint generated by default as identity primary key,
	nomor_po text not null unique,
	supplier text not null,
	tanggal date not null default current_date,
	total_biaya_tambahan numeric(14, 2) not null default 0 check (total_biaya_tambahan >= 0),
	metode_alokasi text not null default 'quantity' check (metode_alokasi = 'quantity'),
	invoice_path text,
	created_at timestamptz not null default now()
);

alter table public.pembelian_po add column if not exists invoice_path text;

alter table public.pembelian add column if not exists po_id bigint;
do $$
begin
	if not exists (select 1 from pg_constraint where conname = 'pembelian_po_id_fkey' and conrelid = 'public.pembelian'::regclass) then
		alter table public.pembelian add constraint pembelian_po_id_fkey
			foreign key (po_id) references public.pembelian_po(id) on delete restrict;
	end if;
end $$;

alter table public.pembelian add column if not exists biaya_tambahan numeric(14, 2) not null default 0;
alter table public.pembelian add column if not exists created_at timestamptz not null default now();

do $$
begin
	if not exists (select 1 from pg_constraint where conname = 'pembelian_biaya_tambahan_nonnegative' and conrelid = 'public.pembelian'::regclass) then
		alter table public.pembelian add constraint pembelian_biaya_tambahan_nonnegative check (biaya_tambahan >= 0);
	end if;
end $$;

create table if not exists public.penjualan (
	id bigint generated by default as identity primary key,
	produk_id bigint not null references public.produk(id) on delete restrict,
	qty integer not null check (qty > 0),
	harga_jual numeric(14, 2) not null check (harga_jual >= 0),
	diskon numeric(14, 2) not null default 0 check (diskon >= 0),
	hpp_saat_transaksi numeric(14, 2) not null default 0 check (hpp_saat_transaksi >= 0),
	total numeric(14, 2) not null check (total >= 0),
	tanggal date not null default current_date,
	created_at timestamptz not null default now()
);

alter table public.penjualan add column if not exists diskon numeric(14, 2) not null default 0;
alter table public.penjualan add column if not exists created_at timestamptz not null default now();

do $$
begin
	if not exists (select 1 from pg_constraint where conname = 'penjualan_diskon_valid' and conrelid = 'public.penjualan'::regclass) then
		alter table public.penjualan add constraint penjualan_diskon_valid check (diskon >= 0 and diskon <= qty * harga_jual);
	end if;
end $$;

create table if not exists public.penyesuaian_stok (
	id bigint generated by default as identity primary key,
	produk_id bigint not null references public.produk(id) on delete restrict,
	tipe text not null check (tipe in ('masuk', 'keluar')),
	qty integer not null check (qty > 0),
	alasan text not null default '',
	tanggal date not null default current_date,
	hpp_saat_transaksi numeric(14, 2) not null default 0 check (hpp_saat_transaksi >= 0),
	created_at timestamptz not null default now()
);

alter table public.penyesuaian_stok
	add column if not exists hpp_saat_transaksi numeric(14, 2) not null default 0;

-- Pastikan transaksi penjualan lama juga memiliki snapshot HPP.
alter table public.penjualan
	add column if not exists hpp_saat_transaksi numeric(14, 2) not null default 0;

create index if not exists pembelian_produk_tanggal_idx
	on public.pembelian (produk_id, tanggal desc);
create index if not exists pembelian_po_idx
	on public.pembelian (po_id);
create index if not exists penjualan_produk_tanggal_idx
	on public.penjualan (produk_id, tanggal desc);
create index if not exists penyesuaian_produk_tanggal_idx
	on public.penyesuaian_stok (produk_id, tanggal desc);

alter table public.produk enable row level security;
alter table public.pembelian enable row level security;
alter table public.pembelian_po enable row level security;
alter table public.penjualan enable row level security;
alter table public.penyesuaian_stok enable row level security;

drop policy if exists "development access produk" on public.produk;
create policy "development access produk" on public.produk
	for all to anon, authenticated using (true) with check (true);

drop policy if exists "development access pembelian" on public.pembelian;
create policy "development access pembelian" on public.pembelian
	for all to anon, authenticated using (true) with check (true);

drop policy if exists "development access pembelian po" on public.pembelian_po;
create policy "development access pembelian po" on public.pembelian_po
	for all to anon, authenticated using (true) with check (true);

drop policy if exists "development access penjualan" on public.penjualan;
create policy "development access penjualan" on public.penjualan
	for all to anon, authenticated using (true) with check (true);

drop policy if exists "development access penyesuaian stok" on public.penyesuaian_stok;
create policy "development access penyesuaian stok" on public.penyesuaian_stok
	for all to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on public.produk to anon, authenticated;
grant select, insert, update, delete on public.pembelian to anon, authenticated;
grant select, insert, update, delete on public.pembelian_po to anon, authenticated;
grant select, insert, update, delete on public.penjualan to anon, authenticated;
grant select, insert, update, delete on public.penyesuaian_stok to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Invoice disimpan privat; UI membuat signed URL sementara untuk preview/download.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('invoice-vendor', 'invoice-vendor', false, 10485760, array['application/pdf', 'image/jpeg', 'image/png'])
on conflict (id) do update set
	public = false,
	file_size_limit = excluded.file_size_limit,
	allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "development invoice vendor access" on storage.objects;
create policy "development invoice vendor access" on storage.objects
	for all to anon, authenticated
	using (bucket_id = 'invoice-vendor')
	with check (bucket_id = 'invoice-vendor');

-- Bila schema cache belum diperbarui setelah pembuatan tabel, jalankan:
notify pgrst, 'reload schema';